# -*- coding: utf-8 -*-
"""turicreate

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PMwsjUEdfzAgB6gTzIw_PaGV8gbpZvgf
"""

pip install turicreate

import turicreate as tc

cancer = tc.SFrame('data.csv')
cancer

type(cancer)

cancer

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cancer["diagnosis"] = le.fit_transform(cancer["diagnosis"])

cancer["diagnosis"].value_counts()

columns = cancer[["radius_mean","perimeter_mean","area_mean","compactness_mean","concavity_mean","concave points_mean",
                  "radius_se","perimeter_se","area_se","radius_worst","perimeter_worst","area_worst","compactness_worst",
                  "concavity_worst","concave points_worst","diagnosis"]]

cancer.shape

plt.pie(cancer["diagnosis"].value_counts())
plt.show()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cancer["diagnosis"] = le.fit_transform(cancer["diagnosis"])

columns